name: 'Expo build:ios with 2FA support'

description: 'Runs upload:ios on an Expo process, allowing for manual 2FA entry via ngrok tunnel'

inputs:
    expo_arguments:
      description: "Any additional arguments you'd like to provide to expo upload:ios"
      required: false
    expo_apple_id:
      description: "Apple ID to use"
      required: true
    expo_apple_password:
      description: "Your Apple password"
      required: true
    tfa_phone_number:
      description: "The phone number to text for 2FA"
      required: true
    app_specific_password:
      description: "App-specific password for Transporter to use"
      required: true
    transporter_email:
      description: "Email to send the message from"
      required: true
    receiver_email:
      description: "Email to send the message to"
      required: true  
    sendgrid_api_key:
      description: "Sendgrip developer API key"
      required: true 
    sendgrid_email_to:
      description: "The email to send the message to"
      required: true
    sendgrid_email_from:
      description: "The email to send the message from"
      required: true
       

branding:
  color: green
  icon: smartphone

runs:
  using: 'node12'
  main: 'index.js'
  pre: 'chalk.js'
